name: Publish package to GitHub Packages

on:
  release:
    types: [created]

env:
  TZ: Pacific/Noumea

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Publish package
        env:
          REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
        run: |
          echo "<settings><servers><server><id>github</id><username>DSI-Ville-Noumea</username><password>${REPO_GITHUB_TOKEN}</password></server></servers></settings>" > settings.xml
          mvn deploy --settings settings.xml
